### PR TITLE
Correct binary

### PR DESCRIPTION
**Pull request by bjornhij**

### CODE REVIEW

**Comment by sweetpi** [comment]
So what is the difference? The current one is compiled with newest wiringX on the rpi1.

**Comment by bjornhij** [comment]
It doesnt work on a rpi2.. Unknown hardware. My binary does work on a rpi2.

**Comment by sweetpi** [comment]
Hm very interesting, so seems like I used accidentally not the newes wiringX,... Thank you, I will update it with yours.

**Comment by bjornhij** [comment]
thx!

**Pull request merged**
